(function(){'use strict';
// explicit route: router > internet
var listeners=[], state={view:'home',status:'idle',server:{name:'Auto',sponsor:'',city:'',latency:'—'},history:[],metrics:{},isp:'ISP',connection:'Wi‑Fi',range:7,servers:[]};
function notify(){listeners.forEach(function(fn){fn(state)})}
function subscribe(fn){listeners.push(fn);return function(){listeners=listeners.filter(function(x){return x!==fn})}}
var adapter={call:function(){return Promise.reject(new Error('Speedtest adapter not configured'))},subscribe:subscribe,navigate:function(view){state.view=view;render();notify()}};
try { if (typeof window !== 'undefined' && window.SpeedtestWebAdapter) adapter=window.SpeedtestWebAdapter; else if (window.parent && window.parent !== window && window.parent.SpeedtestWebAdapter) adapter=window.parent.SpeedtestWebAdapter; } catch (_) {}
function el(id){return document.getElementById(id)} function text(node,value){if(node)node.textContent=value}
function render(){text(el('status'),state.status==='running'?'Testing…':state.status==='error'?'Test failed':state.status==='done'?'Test complete':'Ready to test your connection');text(el('metrics'),state.metrics.download!=null?'Download '+state.metrics.download+' · Upload '+state.metrics.upload+' · Ping '+state.metrics.ping:'');text(el('isp-badge'),state.isp||'ISP');text(el('network-badge'),state.connection||'Connection');text(el('server-name'),state.server.name);text(el('server-detail'),[state.server.sponsor,state.server.city,state.server.latency!=='—'?'Latency '+state.server.latency+' ms':''].filter(Boolean).join(' · ')||'Select a server');var v=el('view');if(!v)return;while(v.firstChild)v.removeChild(v.firstChild);if(state.view==='history')renderHistory(v);else if(state.view==='analytics')renderAnalytics(v);else if(state.view==='settings')v.appendChild(document.createTextNode('Settings'));else if(state.view==='about')v.appendChild(document.createTextNode('Powered by Ookla Speedtest'))}
function renderHistory(v){var h=document.createElement('h2');h.textContent='History';v.appendChild(h);var table=document.createElement('table');var cap=document.createElement('caption');cap.textContent='Speed test history';table.appendChild(cap);var head=document.createElement('thead');var hr=document.createElement('tr');['Date','Download','Upload','Ping','Server','Actions'].forEach(function(x){var th=document.createElement('th');th.textContent=x;th.setAttribute('scope','col');hr.appendChild(th)});head.appendChild(hr);table.appendChild(head);state.history.forEach(function(r,i){var tr=document.createElement('tr');['date','download','upload','ping','server'].forEach(function(k){var td=document.createElement('td');td.textContent=r[k]||'—';tr.appendChild(td)});var d=document.createElement('button');d.textContent='Delete';d.onclick=function(){Promise.resolve().then(function(){return adapter.call('delete_history',{id:r.id||i})}).then(function(){var ix=state.history.indexOf(r);if(ix>=0)state.history.splice(ix,1);render();notify()}).catch(function(){state.status='error';render();notify()})};var td=document.createElement('td');td.appendChild(d);tr.appendChild(td);table.appendChild(tr)});v.appendChild(table);var b=document.createElement('button');b.textContent='Clear history';b.onclick=function(){Promise.resolve().then(function(){return adapter.call('clear_history',{})}).then(function(){state.history=[];render();notify()}).catch(function(){state.status='error';render();notify()})};v.appendChild(b)}
function renderAnalytics(v){var h=document.createElement('h2');h.textContent='Analytics';v.appendChild(h);[7,30,0].forEach(function(r){var b=document.createElement('button');b.textContent=r?r+' days':'All';b.onclick=function(){state.range=r;render();notify()};v.appendChild(b)});var s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 300 80');s.setAttribute('role','img');s.setAttribute('aria-label','Speed test trend');var path=document.createElementNS('http://www.w3.org/2000/svg','path');var now=Date.now(), pts=state.history.filter(function(r){if(!state.range)return true;var t=Date.parse(r.date||'');return !isNaN(t)&&t<=now&&now-t<=state.range*86400000;});var d=pts.length?'M0 65 L'+Math.min(290,pts.length*40)+' '+(20+pts.length*5):'M0 65 L50 40 L100 50 L150 20 L200 35 L250 15 L300 25';path.setAttribute('d',d);path.setAttribute('fill','none');path.setAttribute('stroke','currentColor');s.appendChild(path);v.appendChild(s)}
function start(){if(state.status==='running')return;state.status='running';render();notify();Promise.resolve().then(function(){return adapter.call('runTest',{})}).then(function(result){state.status='done';result=result||{};if(result.server)state.server=result.server;state.metrics={download:result.download,upload:result.upload,ping:result.ping};state.isp=result.isp||state.isp;state.connection=result.connection||state.connection;state.history.unshift({id:Date.now(),date:new Date().toISOString(),download:result.download,upload:result.upload,ping:result.ping,server:state.server.name});render();notify()}).catch(function(){state.status='error';render();notify()})}
document.addEventListener('DOMContentLoaded',function(){el('go-control').addEventListener('click',start);document.querySelectorAll('[data-view]').forEach(function(b){b.addEventListener('click',function(){adapter.navigate(b.getAttribute('data-view'))})});el('server-picker').addEventListener('click',function(){el('server-panel').hidden=false;el('server-search').focus();if(!state.servers.length)Promise.resolve().then(function(){return adapter.call('servers',{})}).then(function(x){state.servers=x||[];render();notify()}).catch(function(){state.status='error';render();notify()})});el('server-search').addEventListener('input',function(){var q=(this.value||'').toLowerCase(),box=el('server-results');while(box.firstChild)box.removeChild(box.firstChild);state.servers.filter(function(s){return s&&s.name&&(!q||s.name.toLowerCase().indexOf(q)>=0)}).forEach(function(s){var b=document.createElement('button');b.textContent=s.name+' '+(s.city||'');b.onclick=function(){state.server=s;el('server-panel').hidden=true;render();notify()};box.appendChild(b)})});render()});
if(typeof window!=='undefined')window.SpeedtestWeb={adapter:adapter,state:state,render:render};
})();
