const fs=require('fs');const path=require('path');const assert=require('assert');
const root=path.join(__dirname,'..','package','shared','ookla-speedtest-web');
for(const f of ['index.html','gauge.js','app.js','styles.css']) assert.ok(fs.existsSync(path.join(root,f)),`missing ${f}`);
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'); const js=fs.readFileSync(path.join(root,'app.js'),'utf8'); const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');
const makefile=fs.readFileSync(path.join(__dirname,'..','package','Makefile'),'utf8');const version=makefile.match(/^PKG_VERSION:=(\S+)$/m)[1];const escapedVersion=version.replaceAll('.','\\.');
for(const [asset,attribute] of [['styles.css','href'],['gauge.js','src'],['app.js','src']]) assert.match(html,new RegExp(`${attribute}=["']${asset.replaceAll('.','\\.')}\\?v=${escapedVersion}["']`));
assert.match(html,new RegExp(`<script src=["']gauge\\.js\\?v=${escapedVersion}["']><\\/script>\\s*<script src=["']app\\.js\\?v=${escapedVersion}["']><\\/script>`));
assert.match(html,/id=["']go-control["']/); assert.match(html,/History/); assert.match(html,/Analytics/); assert.match(html,/Settings/); assert.match(html,/About/);
for(const id of ['live-gauge','gauge-needle','gauge-value','gauge-unit','phase-label','metric-download','metric-upload','metric-ping','metric-jitter','metric-loss','download-trace','upload-trace','cancel-test']) assert.match(html,new RegExp(`id=["']${id}["']`),`missing semantic gauge node #${id}`);
for(const id of ['phase-announcer','error-message','retry-test']) assert.match(html,new RegExp(`id=["']${id}["']`),`missing recovery/accessibility node #${id}`);
const stageStart=html.indexOf('id="test-stage"'),resultsStart=html.indexOf('id="results"'),stageEnd=html.indexOf('</section>',stageStart);assert.ok(stageStart>=0&&resultsStart>stageStart&&resultsStart<stageEnd,'results must belong to the test stage');
const arc=html.match(/class="gauge-track" d="M([\d.]+) ([\d.]+) A[\d. ]+ ([\d.]+) ([\d.]+)"/);assert.ok(arc,'missing gauge arc geometry');
const needle=html.match(/id="gauge-needle"[^>]*>[\s\S]*?<line x1="([\d.]+)" y1="([\d.]+)" x2="([\d.]+)" y2="([\d.]+)"/);assert.ok(needle,'missing gauge needle geometry');
function rotateNeedle(angle){const cx=+needle[1],cy=+needle[2],x=+needle[3]-cx,y=+needle[4]-cy,r=angle*Math.PI/180;return{x:cx+x*Math.cos(r)-y*Math.sin(r),y:cy+x*Math.sin(r)+y*Math.cos(r)}}
function assertAligned(point,endX,endY,message){const cx=+needle[1],cy=+needle[2],ax=point.x-cx,ay=point.y-cy,bx=endX-cx,by=endY-cy;assert.ok(Math.abs(ax*by-ay*bx)<1e-6&&ax*bx+ay*by>0,message)}
assertAligned(rotateNeedle(-135),+arc[1],+arc[2],'zero-speed needle must point at the lower-left dial endpoint');
assertAligned(rotateNeedle(135),+arc[3],+arc[4],'max-speed needle must point at the lower-right dial endpoint');
assert.match(html,/id=["']live-announcer["'][^>]*aria-live=["']polite["'][^>]*data-throttle-ms=["']\d+["']/);
assert.match(html,/id=["']phase-announcer["'][^>]*aria-live=["']polite["']/);
assert.match(html,/id=["']download-trace-label["']/);assert.match(html,/id=["']upload-trace-label["']/);
assert.match(html,/id=["']retry-test["'][^>]*>Retry</);
assert.match(html,/id=["']primary-metrics["'][^>]*hidden/);assert.match(html,/class=["']latency-strip["'][^>]*hidden/);
assert.match(html,/id=["']gauge-dial["']/);assert.match(html,/id=["']gauge-readout["']/);
assert.match(html,/Router\s*→\s*Internet/); assert.match(html,/Device\s*→\s*Router/);
assert.match(js,/subscribe\s*\(/); assert.match(js,/navigate\s*\(/); assert.match(js,/call\s*\(/); assert.match(js,/textContent/); assert.doesNotMatch(js,/innerHTML/);
assert.match(js,/function renderGauge\s*\(/); assert.match(js,/SpeedtestGauge\.angleFor/); assert.match(js,/SpeedtestGauge\.tracePath/);
assert.match(js,/function announceGauge\s*\(/); assert.match(js,/setTimeout\s*\(/);
assert.match(js,/router.*internet|internet.*router/i); assert.match(css,/@media/); assert.match(css,/#0?4|navy|cyan/i);
assert.match(css,/--cyan\s*:/); assert.match(css,/--violet\s*:/); assert.match(css,/:focus-visible/); assert.match(css,/@media\s*\(prefers-reduced-motion:\s*reduce\)/); assert.match(css,/@media\s*\(max-width:\s*640px\)/); assert.match(css,/grid-template-columns:\s*1fr/);
assert.match(css,/\.gauge\[data-status=["']idle["']\]\s+\.gauge-dial/);
assert.match(css,/\.gauge-needle\s*\{[^}]*transform-box:\s*view-box/);
assert.doesNotMatch(html,/id=["']gauge-needle["'][^>]*\stransform=/);
assert.match(css,/\.gauge\s*\{[^}]*width:\s*100%;[^}]*max-width:\s*520px;/s);assert.match(css,/@supports\s*\(aspect-ratio:/);
assert.match(css,/\.gauge\[data-status=["']done["']\]/);
assert.match(css,/\.gauge\[data-status="idle"\],[^{]+\{[^}]*width:\s*clamp\(280px,\s*32vw,\s*340px\)/s,'compact shell must remain reference-sized and responsive');
assert.match(css,/\.go\s*\{[^}]*width:\s*clamp\(190px,\s*20vw,\s*210px\)[^}]*height:\s*clamp\(190px,\s*20vw,\s*210px\)/s,'GO ring must remain large and responsive');
assert.doesNotMatch(css,/\.go\s*\{[^}]*width:\s*(?:78|92)px/s,'GO must not regress to the tiny installed size');
assert.match(css,/@media\s*\(max-width:\s*640px\)[\s\S]*?\.go\s*\{[^}]*clamp\(/,'mobile GO sizing must remain responsive');
assert.match(css,/\.history-scroll\s*\{[^}]*overflow-x:\s*auto/s);
assert.match(css,/\.history-scroll table\s*\{[^}]*min-width:/s);
assert.match(js,/aria-pressed/);assert.match(js,/\.disabled\s*=/);
assert.match(html,/data-mode=["']router-internet["'][^>]*aria-pressed=["']true["']/);
assert.match(html,/data-mode=["']device-router["'][^>]*aria-pressed=["']false["']/);
for(const mode of ['router-internet','device-router','both']) assert.match(html,new RegExp(`data-mode=["']${mode}["']`));
assert.match(js,/local_download/); assert.match(js,/local_upload/); assert.match(js,/Promise\.all/);
assert.match(js,/size=32768/); assert.doesNotMatch(js,/size=131072/);
assert.match(js,/Router → Internet/); assert.match(js,/Device → Router/);
const luci=path.join(__dirname,'..','package','luci-app-ookla-speedtest-web'); const gl=path.join(__dirname,'..','package','gl-app-ookla-speedtest-web');
for(const f of ['usr/share/luci/menu.d/luci-app-ookla-speedtest-web.json','www/luci-static/resources/view/ookla-speedtest-web/main.js','usr/libexec/rpcd/ookla-speedtest-web']) assert.ok(fs.existsSync(path.join(luci,f)),`missing ${f}`);
for(const f of ['CONTROL/control','CONTROL/postinst','usr/share/oui/menu.d/ookla-speedtest-web.json','usr/lib/oui-httpd/rpc/ookla-speedtest-web','www/views/gl-sdk4-ui-ookla-speedtest-web.common.js']) assert.ok(fs.existsSync(path.join(gl,f)),`missing ${f}`);
const ljs=fs.readFileSync(path.join(luci,'www/luci-static/resources/view/ookla-speedtest-web/main.js'),'utf8'); assert.match(ljs,/view\.extend/); assert.match(ljs,/rpc\.declare/); assert.match(ljs,/csrf|session|authenticated/i); assert.doesNotMatch(ljs,/https?:\/\//);
assert.match(ljs,/frame\.src\s*=\s*L\.resource\(['"]ookla-speedtest-web\/index\.html['"]\)/);
assert.match(ljs,/window\.SpeedtestWebAdapter/);
assert.match(ljs,/start_live\s*:\s*\[\s*['"]server_id['"]\s*\]/);
assert.match(ljs,/live_status\s*:\s*\[\s*['"]job_id['"]\s*\]/);
assert.match(ljs,/cancel_live\s*:\s*\[\s*['"]job_id['"]\s*\]/);
assert.match(ljs,/begin_local\s*:\s*\[\s*\]/);
assert.match(ljs,/cancel_local\s*:\s*\[\s*['"]run_id['"]\s*\]/);
assert.match(ljs,/local_download\s*:\s*\[\s*['"]run_id['"]\s*,\s*['"]bytes['"]\s*\]/);
assert.match(ljs,/local_upload\s*:\s*\[\s*['"]run_id['"]\s*,\s*['"]data['"]\s*\]/);
assert.match(ljs,/record_local\s*:\s*\[\s*['"]run_id['"]\s*,\s*['"]download_mbps['"]\s*,\s*['"]upload_mbps['"]\s*,\s*['"]ping_ms['"]\s*\]/);
const lrpc=fs.readFileSync(path.join(luci,'usr/libexec/rpcd/ookla-speedtest-web'),'utf8'); assert.match(lrpc,/list|call/); assert.match(lrpc,/OOKLA_SPEEDTEST_BIN/); assert.doesNotMatch(lrpc,/\$\(.*\)|`/);
const gr=fs.readFileSync(path.join(gl,'usr/lib/oui-httpd/rpc/ookla-speedtest-web'),'utf8');
assert.match(gr,/local M\s*=\s*\{\}/);
assert.match(gr,/function M\.settings/);
assert.match(gr,/function M\.local_download/);
assert.match(gr,/function M\.local_upload/);
assert.match(gr,/function M\.begin_local\s*\(params\)\s*return invoke\(["']begin_local["'],\s*params\) end/);
assert.match(gr,/function M\.cancel_local\s*\(params\)\s*return invoke\(["']cancel_local["'],\s*params\) end/);
assert.match(gr,/function M\.start_live\s*\(params\)\s*return invoke\(["']start_live["'],\s*params\) end/);
assert.match(gr,/function M\.live_status\s*\(params\)\s*return invoke\(["']live_status["'],\s*params\) end/);
assert.match(gr,/function M\.cancel_live\s*\(params\)\s*return invoke\(["']cancel_live["'],\s*params\) end/);
assert.match(gr,/stdout_read_timeout\s*=\s*timeout\s+or\s+30000/);
assert.match(gr,/function M\.start\s*\(params\)\s*return invoke\(["']start["'],\s*params,\s*130000\) end/);
for(const method of ['start_live','live_status','cancel_live']) assert.doesNotMatch(gr,new RegExp(`function M\\.${method}[^\\n]*130000`));
assert.match(gr,/return M/);
assert.doesNotMatch(gr,/^#!\/bin\/sh/m);
assert.doesNotMatch(gr,/\/usr\/libexec\/rpcd\/ookla-speedtest-web/);
assert.doesNotMatch(gr,/listen|port|password|credential/i);
const gm=JSON.parse(fs.readFileSync(path.join(gl,'usr/share/oui/menu.d/ookla-speedtest-web.json'),'utf8'));
assert.strictEqual(gm.parent,'applications'); assert.strictEqual(gm.level,2); assert.strictEqual(gm.view,'ookla-speedtest-web'); assert.strictEqual(gm.title,'Ookla Speedtest');
const gv=fs.readFileSync(path.join(gl,'www/views/gl-sdk4-ui-ookla-speedtest-web.common.js'),'utf8'); assert.match(gv,/window\.SpeedtestWebAdapter/); assert.match(gv,/module\.exports/); assert.match(gv,/window\.\$request/); assert.match(gv,/srcdoc/); assert.match(gv,/<base href=/); assert.doesNotMatch(gv,/sysauth/); assert.doesNotMatch(gv,/\.src\s*=\s*['"]\/luci-static/);
const glSrcdoc=html.replace('<head>','<head><base href="/luci-static/resources/ookla-speedtest-web/">');for(const asset of ['styles.css','gauge.js','app.js']) assert.ok(glSrcdoc.includes(`${asset}?v=${version}`),`GL srcdoc must preserve ${asset} cache key`);
console.log('frontend contract ok');
